<a href="https://colab.research.google.com/github/arfaizzarayhani/NumericalMethod/blob/main/MetNum4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
u = np.array([1, 2, 3])

A = np.array([[-2, 1, 2], [7, 0, 5], [2, -1, 3]])
print(A)
print("Transpose A:\n", A.T)

B = np.array([[5, 7, -1], [2, -8, -9], [1, 2, 3]])
print("Matriks B:\n", B)
print("Perkalian A * B =\n", A@B)

[[-2  1  2]
 [ 7  0  5]
 [ 2 -1  3]]
Transpose A:
 [[-2  7  2]
 [ 1  0 -1]
 [ 2  5  3]]
Matriks B:
 [[ 5  7 -1]
 [ 2 -8 -9]
 [ 1  2  3]]
Perkalian A * B =
 [[ -6 -18  -1]
 [ 40  59   8]
 [ 11  28  16]]


In [21]:
from scipy.linalg import lu

A = np.array([[-2, 1, 2], [7, 0, 5], [2, -1, 3]])
P, L, U = lu(A)
print("L =\n", L)
print("U =\n", U)


L =
 [[ 1.          0.          0.        ]
 [-0.28571429  1.          0.        ]
 [ 0.28571429 -1.          1.        ]]
U =
 [[7.         0.         5.        ]
 [0.         1.         3.42857143]
 [0.         0.         5.        ]]


In [22]:
from scipy.linalg import qr
A = np.array([[-2, 1, 2], [7, 0, 5], [2, -1, 3]])
Q, R = qr(A)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[-0.26490647 -0.65561007  0.70710678]
 [ 0.92717265 -0.37463432  0.        ]
 [ 0.26490647  0.65561007  0.70710678]]
R:
 [[ 7.54983444 -0.52981294  4.90076972]
 [ 0.         -1.31122014 -1.21756156]
 [ 0.          0.          3.53553391]]


In [23]:
A = np.array([[-2, 1, 2], [7, 0, 5], [2, -1, 3]])
vals, vecs = np.linalg.eig(A)
print("Nilai Eigen:\n", vals)
print("Vektor Eigen:\n", vecs)

Nilai Eigen:
 [-4.06685449+0.j         2.53342724+1.4791573j  2.53342724-1.4791573j]
Vektor Eigen:
 [[ 0.62383659+0.j         -0.25940278-0.02257034j -0.25940278+0.02257034j]
 [-0.72974709+0.j         -0.92825737+0.j         -0.92825737-0.j        ]
 [-0.27981619+0.j         -0.1071706 -0.24300926j -0.1071706 +0.24300926j]]
